version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Halifax
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: jest
    versions:
    - "*"
  - dependency-name: jest-cli
    versions:
    - "*"
  - dependency-name: puppeteer
    versions:
    - "*"
  - dependency-name: "@types/jest"
    versions:
    - "*"
  - dependency-name: "@stencil/core"
    versions:
    - 2.4.0
    - 2.5.0
    - 2.5.1
