/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Connection, } from "./components/manifold-init/manifold-init";
export namespace Components {
    interface ConnectedButton {
    }
    interface ManifoldInit {
        "authToken"?: string;
        "authType"?: "manual" | "oauth";
        "clientId"?: string;
        "env"?: "local" | "stage" | "prod";
        "initialize": (options: {
            element: HTMLElement;
            componentVersion: string;
            version: number;
        }) => Promise<Connection>;
    }
}
declare global {
    interface HTMLConnectedButtonElement extends Components.ConnectedButton, HTMLStencilElement {
    }
    var HTMLConnectedButtonElement: {
        prototype: HTMLConnectedButtonElement;
        new (): HTMLConnectedButtonElement;
    };
    interface HTMLManifoldInitElement extends Components.ManifoldInit, HTMLStencilElement {
    }
    var HTMLManifoldInitElement: {
        prototype: HTMLManifoldInitElement;
        new (): HTMLManifoldInitElement;
    };
    interface HTMLElementTagNameMap {
        "connected-button": HTMLConnectedButtonElement;
        "manifold-init": HTMLManifoldInitElement;
    }
}
declare namespace LocalJSX {
    interface ConnectedButton {
    }
    interface ManifoldInit {
        "authToken"?: string;
        "authType"?: "manual" | "oauth";
        "clientId"?: string;
        "env"?: "local" | "stage" | "prod";
        "onManifold-auth-token-clear"?: (event: CustomEvent<any>) => void;
        "onManifold-auth-token-receive"?: (event: CustomEvent<string>) => void;
    }
    interface IntrinsicElements {
        "connected-button": ConnectedButton;
        "manifold-init": ManifoldInit;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "connected-button": LocalJSX.ConnectedButton & JSXBase.HTMLAttributes<HTMLConnectedButtonElement>;
            "manifold-init": LocalJSX.ManifoldInit & JSXBase.HTMLAttributes<HTMLManifoldInitElement>;
        }
    }
}
